### ISSUE TITLE
After creating a new post in GraphCMS, the new post doesn't appear in the deployed version

### ISSUE THREAD

**Issue by fransachmadhw** [adrianhajdin/project_graphql_blog#25]
That post appears only in localhost. In deployed version, it doesn't. A bit weird, that post doesn't appear on the home page and category page. However, in featured post cards and recent posts, it does. Anyone knows how to fix it?

**Comment by JoBaHP** [comment]
Where are you hosting your app?

**Comment by fransachmadhw** [comment]
> Where are you hosting your app? 

Vercel. Same as what he did in the video

**Comment by JoBaHP** [comment]
For me is because i am statically exporting my app to my host provider and is behavior i expect.

**Comment by fransachmadhw** [comment]
> For me is because i am statically exporting my app to my host provider and is behavior i expect.

So, does the problem come from my code? Or from vercel?

**Comment by kutukmu** [comment]
I have the same issue right now, did you figure out the solution?

**Comment by fransachmadhw** [comment]
> I have the same issue right now, did you figure out the solution?

Not yet haha

**Comment by kutukmu** [comment]
return {
    props: { posts },
    revalidate: 10
  };
try this

**Comment by fransachmadhw** [comment]
> return { props: { posts }, revalidate: 10 }; try this

It works like a charm. I just discovered what revalidate does in next.js docs too. Thanks in advance

**Comment by JerwellSavella** [comment]
@kutukmu which file should I add this? should I create a new file? which folder should I add it to?

**Comment by fransachmadhw** [comment]
> @kutukmu which file should I add this? should I create a new file? which folder should I add it to?

On page/index.js

**Comment by JerwellSavella** [comment]
> > @kutukmu which file should I add this? should I create a new file? which folder should I add it to?
> 
> On page/index.js

still doesn't work for me,

**Comment by fransachmadhw** [comment]
> > > @kutukmu which file should I add this? should I create a new file? which folder should I add it to?
> > 
> > On page/index.js
> 
> still doesn't work for me,
> 

@JerwellSavella see my repository as a reference
https://github.com/fransachmadhw/blogshot-clone
