### ISSUE TITLE
Error token verification failed: token contains an invalid number of segments

### ISSUE THREAD

**Issue by Ruu-hub** [adrianhajdin/project_graphql_blog#53]
ClientError: GraphQL Error (Code: 401): {"response":{"error":"{\"errors\":[{\"message\":\"token verification failed: token contains an invalid number of segments\"}],\"data\":null}","status":401,"headers":{}},"request":{"query":"\n    mutation CreateComment($name: String!, $comment: String!, $slug: String!) {\n      createComment(data: {name: $name, comment: $comment, post: {connect: {slug: $slug}}}) { id }\n    }\n  ","variables":{"name":"ksad","comment":"adasd","slug":"pemdas"}}}

**Comment by Ruu-hub** [comment]
Solved i just typo during process.env

**Comment by Zweli-Sa** [comment]
What did you do? would you mind elaborating the steps perhaps?
